-- Run this SQL in your Supabase SQL Editor (https://supabase.com/dashboard/project/zipqopowyrcsnpgjcdoi/sql/new)
-- This will fix permission issues, clear all medicines, and insert the Fatpizza Kitchen items.

-- Step 1: Disable Row Level Security and grant full access to allow Admin Panel updates
ALTER TABLE public.medicines DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.medicines TO anon, authenticated, service_role;

-- Step 2: Clear existing medicines table
TRUNCATE TABLE public.medicines;

-- Step 2: Insert the Fatpizza Menu Items
INSERT INTO public.medicines (id, name, generic_name, category, price_pkr, stock, dosage, description, manufacturer, requires_prescription, image_url) VALUES
(1, 'Veggie Lover Pizza', 'Mushrooms, Olives, Bell Peppers, Onions & Mozzarella', 'Pizza', 990, 50, '12 inch Medium', 'A colorful medley of fresh garden vegetables, sliced mushrooms, black olives, sweet bell peppers, and red onions on a rich tomato base, covered in gooey mozzarella.', 'Fatpizza Kitchen', false, 'https://www.thegraciouspantry.com/wp-content/uploads/2023/06/veggie-pizza-recipe-v-1-.jpg'),
(2, 'Cheese Lover', 'Loaded Mozzarella, Cheddar, Parmesan & Herb Sauce', 'Pizza', 890, 60, '12 inch Medium', 'The ultimate cheese dream. Thick layers of imported mozzarella, sharp cheddar, and fresh parmesan, finished with Italian herbs on our signature thin crust.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80'),
(3, 'Afghani Feast', 'Charcoal Grilled Afghani Boti, Onions & White Garlic Sauce', 'Pizza', 1190, 45, '12 inch Medium', 'An authentic culinary feast featuring tender Afghani-style chicken tikka cubes, red onions, fresh coriander, and a drizzle of rich garlic sauce.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1604917621956-10dfa7cce2e7?w=600&auto=format&fit=crop&q=80'),
(4, 'Chicken Supreme', 'Smoked Chicken chunks, Chicken Salami, Bell Peppers & Olives', 'Pizza', 1150, 40, '12 inch Medium', 'For true meat and supreme lovers. Smoked chicken chunks, spicy chicken salami, red onions, mushrooms, green bell peppers, and sliced black olives.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80'),
(5, 'Chk Supreme', 'Spiced Chicken Tikka, Fajita Strips & Mozzarella', 'Pizza', 1100, 55, '12 inch Medium', 'A combination of seasoned chicken tikka chunks and bell peppers topped with melted cheese, baked to crispy perfection.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80'),
(6, 'Chicken Fajita Supreme', 'Sizzling Fajita Chicken, Bell Peppers, Onions & Jalapeños', 'Pizza', 1250, 35, '12 inch Medium', 'Sizzling Mexican-style fajita chicken strips, mixed bell peppers, red onions, and hot jalapeños to give a delicious kick of heat.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80'),
(7, 'BBQ Tikka Pizza', 'Smokey BBQ Tikka Boti, Jalapeño Peppers & Onions', 'Pizza', 1190, 45, '12 inch Medium', 'Perfectly charred chicken tikka pieces infused with smoky sweet BBQ sauce, red onions, green peppers, and lots of mozzarella.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80'),
(8, 'Cheese Sticks', 'Garlic Butter Breadsticks with Melted Mozzarella', 'Sides', 450, 100, '6 Pieces', 'Warm, soft garlic breadsticks loaded with bubbly melted mozzarella cheese, served with a side of marinara dipping sauce.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1531749668029-2db88e4b76ce?w=600&auto=format&fit=crop&q=80'),
(9, 'Pizza Fries', 'Crispy Fries topped with Pizza Sauce, Pepperoni & Cheese', 'Sides', 590, 80, 'Platter', 'Golden crispy french fries layered with rich pizza marinara sauce, melted mozzarella, chopped olives, and sliced pepperoni.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80'),
(10, 'Club Sandwich', 'Triple-Decker Grilled Chicken, Fried Egg, Cheese & Lettuce', 'Sandwich', 650, 40, 'Standard Serving', 'Classic toasted triple-decker sandwich with seasoned grilled chicken, a fried egg, cheddar cheese slices, crisp lettuce, tomato, and mayo.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=600&auto=format&fit=crop&q=80'),
(11, 'Mexican Chicken Sandwich', 'Spicy Mexican Seasoned Chicken Breast, Salsa & Jalapeños', 'Sandwich', 690, 35, 'Standard Serving', 'Toasted pan-pressed sandwich loaded with shredded chicken in spicy Mexican salsa, jalapeño rings, and melted pepper jack cheese.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=600&auto=format&fit=crop&q=80'),
(12, 'Kabab Chaska Pizza', 'Traditional Seekh Kabab slices, Green Chilies & Yogurt Mint Drizzle', 'Pizza', 1290, 30, '12 inch Medium', 'A fusion masterpiece featuring sliced traditional seekh kababs, sharp green chilies, onions, coriander, and a drizzle of spicy yogurt mint chutney.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80'),
(13, 'Zinger Burger', 'Crispy Golden Fried Chicken Fillet, Mayo & Iceberg Lettuce', 'Burger', 550, 90, 'Classic Zinger', 'Super crispy, golden-fried spicy chicken breast fillet in a soft toasted sesame bun, topped with creamy mayonnaise and crunchy shredded lettuce.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80'),
(14, 'Creamy Pizza', 'Rich Cream Sauce, Grilled Chicken, Mushrooms & Parsley', 'Pizza', 1200, 45, '12 inch Medium', 'Creamy white Alfredo base sauce topped with tender sliced grilled chicken breast, button mushrooms, parsley, and premium cheese blend.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1594007654729-407ededc414a?w=600&auto=format&fit=crop&q=80'),
(15, 'Cheese n Pepperoni Pizza', 'Gooey Mozzarella & Lots of Spicy Pepperoni Slices', 'Pizza', 1150, 50, '12 inch Medium', 'A true American classic. Rich tomato base, generous layers of premium mozzarella, topped to the edge with loads of crispy sliced pepperoni.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80'),
(16, 'Chicken BBQ Wings', 'Tossed in Smokey BBQ Sauce & Garnished with Sesame', 'Sides', 490, 75, '8 Pieces', 'Juicy, tender chicken wings deep-fried and tossed in a thick, sticky, smoky hickory BBQ sauce, sprinkled with toasted sesame seeds.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80'),
(17, 'Beef Burger', 'Grilled Beef Patty, Cheddar Cheese, Pickles & Burger Sauce', 'Burger', 650, 50, 'Single Patty', 'Freshly smashed hand-formed prime beef patty grilled to perfection, topped with melted cheddar, pickles, onions, and house burger sauce.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80'),
(18, 'Creamy Fajita Pizza', 'Creamy Base, Seasoned Fajita Chicken, Onions & Peppers', 'Pizza', 1250, 40, '12 inch Medium', 'A combination of our signature rich cream base, marinated chicken fajita slices, colorful bell peppers, and sliced red onions.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80'),
(19, 'Creamy Tikka Pizza', 'Rich Cream Base, Spicy Chicken Tikka Boti & Red Onions', 'Pizza', 1250, 42, '12 inch Medium', 'Spicy chicken tikka chunks set on top of a delicious, velvety creamy white sauce base, baked with premium mozzarella.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1594007654729-407ededc414a?w=600&auto=format&fit=crop&q=80'),
(20, 'Chicken Cheese Creamy Pasta', 'Fettuccine in Rich Alfredo White Sauce with Grilled Chicken & Herbs', 'Pasta', 790, 35, 'Standard Serving', 'Perfectly boiled al dente pasta tossed in a rich, buttery garlic cream sauce, loaded with grilled sliced chicken breast and fresh parsley.', 'Fatpizza Kitchen', false, 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=600&auto=format&fit=crop&q=80');
